---
apiVersion: v1
kind: Service
metadata:
  name: cardano-token-registry
  labels:
    app.kubernetes.io/name: cardano-token-registry
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
  - name: metrics
    port: 3042
    targetPort: 3042
    protocol: TCP
  selector:
    io.kompose.service: cardano-token-registry
