apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dandelion-{{ .Values.cardano.network }}-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.git.repositoryUrl }}
    targetRevision: {{ .Values.git.targetRevision }}
    path: overlays/{{ .Values.cardano.network }}-base
    plugin:
      env:
        - name: CARDANO_NETWORK
          value: {{ .Values.cardano.network }}

  destination:
    namespace: dandelion-{{ .Values.cardano.network }}
    server: {{ .Values.spec.destination.server }}


