{{- if .Values.dandelion.cardano_submit_api.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dandelion-{{ .Values.dandelion.cardano.network }}-cardano-submit-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.git.repositoryUrl }}
    targetRevision: {{ .Values.git.targetRevision }}
    path: base/cardano-submit-api
    plugin:
      name: kustomized-kustomize-network
      env:
        - name: CARDANO_NETWORK
          value: {{ .Values.dandelion.cardano.network }}

  destination:
    namespace: dandelion-{{ .Values.dandelion.cardano.network }}{{ .Values.dandelion.namespaceSuffix }}
    server: {{ .Values.spec.destination.server }}

{{- end }}
