namespace: dandelion-testnet
commonLabels:
  environment: production
  cardano_network: testnet
  cardano_node_type: haskell
  project_name: dandelion
commonAnnotations:
  note: free-apis!

bases:
- ../testnet-base
- ../../base/helm-charts/postgres-ha
- ../../base/cardano-db-sync
- ../../base/cardano-graphql
- ../../base/cardano-hasura
- ../../base/cardano-rosetta
- ../../base/cardano-submit-api
- ../../base/metrics-exporter
- ../../base/ogmios
- ../../base/postgrest
- ../../base/postgres-ws

resources:
- resources/ingress.yaml

patches:
# cardano-node
- path: ../../base/testnet-patches/cardano-node-configmap.yaml
  target:
    kind: ConfigMap
    name: cardano-node
- path: ../../base/testnet-patches/cardano-node-pvc.yaml
  target:
    kind: StatefulSet
    name: cardano-node
- path: ../../base/testnet-patches/cardano-node-deployment-env.yaml
  target:
    kind: StatefulSet
    name: cardano-node
- path: ../../base/testnet-patches/cardano-node-deployment-image.yaml
  target:
    kind: StatefulSet
    name: cardano-node
# cardano-graphql
- path: ../../base/testnet-patches/genesis-image.yaml
  target:
    kind: Deployment
    name: cardano-graphql
# cardano-db-sync
- path: ../../base/testnet-patches/cardano-db-sync-deployment-env.yaml
  target:
    kind: StatefulSet
    name: cardano-db-sync
- path: ../../base/testnet-patches/cardano-db-sync-deployment-image.yaml
  target:
    kind: StatefulSet
    name: cardano-db-sync
# cardano-rosetta
- path: ../../base/testnet-patches/cardano-rosetta-deployment-image.yaml
  target:
    kind: Deployment
    name: cardano-rosetta
# cardano-submit-api
- path: ../../base/testnet-patches/cardano-submit-api-deployment-env.yaml
  target:
    kind: Deployment
    name: cardano-submit-api
# ogmios
- path: ../../base/testnet-patches/ogmios-deployment-env.yaml
  target:
    kind: Deployment
    name: ogmios
