git:
  repositoryUrl: https://gitlab.com/gimbalabs/dandelion/kustomize-dandelion.git
  targetRevision: refactor/add-base-and-multi-node-overlays

dandelion:
  provider:
    name: null
  argoProjectSuffix: "-v9-0-0"
  argoAppSuffix: "-v9-0-0"
  namespaceSuffix: "-v9-0-0"
  multiNode: false
  cardano:
    network: null

spec:
  destination:
    server: https://kubernetes.default.svc
