git:
  repositoryUrl: https://gitlab.com/gimbalabs/dandelion/kustomize-dandelion.git
  targetRevision: main

dandelion:
  provider:
    name: null
  argoProjectSuffix: "v0-0-0"
  argoAppSuffix: "-v0-0-0"
  namespaceSuffix: "-v0-0-0"
  multiNode: false
  cardano:
    network: null

spec:
  destination:
    server: https://kubernetes.default.svc
