apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blockfrost
  name: blockfrost
spec:
  ports:
  - name: blockfrost
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: blockfrost
status:
  loadBalancer: {}
