apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cardano-graphql
  name: cardano-graphql
spec:
  ports:
  - name: "3100"
    port: 3100
    targetPort: 3100
  selector:
    io.kompose.service: cardano-graphql
status:
  loadBalancer: {}
