apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cardano-explorer-api
  name: cardano-explorer-api
spec:
  ports:
  - name: "8101"
    port: 8101
    targetPort: 8100
  selector:
    io.kompose.service: cardano-explorer-api
status:
  loadBalancer: {}
