apiVersion: v1
kind: ConfigMap
metadata:
  name: dandelion-haproxy-configmap
data:
  topology-disabled: |
          { "name": "TICKR",        "addr": "localhost", "port": 443, "protocol": "https" },
  topology-mainnet.json: |  
    {
      "Providers": [
          { "name": "PEACE-sw",     "addr": "v11.mainnet.scw.dandelion.link", "port": 443, "protocol": "https" },
          { "name": "PEACE-soltia", "addr": "soltia.es.dandelion.link", "port": 443, "protocol": "https" },
          { "name": "PEACE-gc",     "addr": "v11.mainnet.gc.scw.dandelion.link", "port": 443, "protocol": "https" },
          { "name": "EASY1",        "addr": "gio.dandelion.link", "port": 443, "protocol": "https" },
          { "name": "RSV",          "addr": "dmn.reservoir.network", "port": 443, "protocol": "https" },
          { "name": "BOOST",        "addr": "baremetal.cardano.dbooster.io", "port": 443, "protocol": "https" },
          { "name": "FLUID7",       "addr": "dandelion.fluid7.com", "port": 443, "protocol": "https" },
          { "name": "saldrich",     "addr": "dandelionflorida.ddns.net", "port": 443, "protocol": "https" }
      ],
      "Consumers": []
    }

  topology-testnet.json: |
    {
      "Providers": [
          { "name": "PEACE-sw",     "addr": "v11.testnet.scw.dandelion.link", "port": 443, "protocol": "https" },
          { "name": "PEACE-soltia", "addr": "soltia.es.dandelion.link", "port": 443, "protocol": "https" },
          { "name": "PEACE-gc",     "addr": "v11.testnet.gc.scw.dandelion.link", "port": 443, "protocol": "https" },
          { "name": "EASY1",        "addr": "gio.dandelion.link", "port": 443, "protocol": "https" },
          { "name": "RSV",          "addr": "dtn.reservoir.network", "port": 443, "protocol": "https" },
          { "name": "BOOST",        "addr": "baremetal.cardano.dbooster.io", "port": 443, "protocol": "https" },
          { "name": "FLUID7",       "addr": "dandelion.fluid7.com", "port": 443, "protocol": "https" },
          { "name": "saldrich",     "addr": "dandelionflorida.ddns.net", "port": 443, "protocol": "https" }
      ],
      "Consumers": []
    }

  graphql-api-healthcheck.tpl: |
    option httpchk
    http-check send meth GET uri / ver HTTP/1.1 hdr host ${INGRESS_DOMAIN}
    http-check expect rstring GET.query.missing
  submit-api-healthcheck.tpl: |
    option httpchk
    http-check send meth POST uri /api/submit/tx ver HTTP/1.1 hdr host ${INGRESS_DOMAIN}
    http-check expect status 415
  explorer-api-healthcheck.tpl: |
    option httpchk
    http-check send meth GET uri /api/txs/last ver HTTP/1.1 hdr host ${INGRESS_DOMAIN}
    http-check expect string cteId
  ogmios-api-healthcheck.tpl: |
    option httpchk
    http-check send meth GET hdr Host ${INGRESS_DOMAIN} hdr Connection Upgrade hdr Upgrade websocket hdr Sec-WebSocket-Key x3JJHMbDL1EzLkh9GBhXDw== hdr Sec-WebSocket-Version 13
    http-check expect status 101
  postgrest-api-healthcheck.tpl: |
    option httpchk
    http-check send meth GET uri /epoch?limit=1 ver HTTP/1.1 hdr host ${INGRESS_DOMAIN}
    http-check expect string out_sum
  rosetta-api-healthcheck.tpl: |
    option httpchk
    http-check send meth GET uri / ver HTTP/1.1 hdr host ${INGRESS_DOMAIN}
    http-check expect rstring message.*Route.GET.*404
  disabled-external-healthcheck: |
    option external-check
    external-check path "/usr/bin:/bin:/tmp:/sbin:/usr/sbin"
    external-check command /configmap/grest-poll.sh
  grest-poll.sh: |
    #!/usr/bin/env sh
    exit 0
    HOSTNAME=postgrest-api.mainnet.dandelion.link
    dbtip=$(curl -k -fL -H "Host: ${HOSTNAME}" -H "Accept: text/plain" "https://${3}/rpc/tip?select=block_time::text" 2>/dev/null)
    currtip=$(TZ='UTC' date "+%Y-%m-%d %H:%M:%S")
    if [[ -n "${dbtip}" ]] ; then
      [[ $(( $(date -d "${currtip}" +%s) - $(date -d "${dbtip}" +%s) )) -lt 180 ]] && exit 0 || echo "ERROR: Tip too far, eliminating from availability" && exit 2
    else
      echo "ERROR: Failed polling for ${3}:${4}, could not query tip"
      exit 1
    fi
  initContainer-entrypoint: |
    #!/bin/bash

    rm -f ${CONFIG_OUTPUT_DIR}/dandelion-haproxy.cfg
    
    # FRONTEND conf
    cat > ${CONFIG_OUTPUT_DIR}/dandelion-haproxy.cfg <<EOF
      frontend main
        mode http
        bind :80
        bind :443 ssl crt /usr/local/etc/ssl/self-signed-ssl.pem
        http-request redirect scheme https code 301 unless { ssl_fc }

        acl is_upgrade hdr(Connection) -i upgrade
        acl is_websocket hdr(Upgrade) -i websocket
    
        acl valid_hosts hdr(host) -m reg -i (${SUB_DOMAIN}.|)($(echo $APIS | sed 's/ /|/g')).($(echo $NETWORKS | sed 's/ /|/g')).${TOP_DOMAIN}$
        acl valid_hosts hdr(host) -m reg -i stats-ian.dandelion.link
        http-request deny if !valid_hosts
    
        use_backend %[req.hdr(Host),lower]
        default_backend no-match
    EOF
    
    # BACKENDS conf

    # stats
    cat >> ${CONFIG_OUTPUT_DIR}/dandelion-haproxy.cfg <<EOF
      backend stats-ian.dandelion.link
        mode http
        stats enable
        stats uri /
        stats hide-version
        stats refresh 10s
        stats admin if LOCALHOST

        option http-use-htx
        http-request use-service prometheus-exporter if { path /metrics }
    EOF

    for network in ${NETWORKS}
    do
    
      for api in ${APIS}
      do
    
        export FQDN="${SUB_DOMAIN}.${api}.${network}.${TOP_DOMAIN}"
        export INGRESS_DOMAIN="${api}.${network}.${TOP_DOMAIN}"
    
        jq -rc .Providers[] ${TOPOLOGY_DIR}/topology-${network}.json | while read provider
        do
          PROVIDER_NAME=$(echo $provider | jq -r .name)
          PROVIDER_HOST=$(echo $provider | jq -r .addr)
          PROVIDER_PORT=$(echo $provider | jq -r .port)
          PROVIDER_PROTO=$(echo $provider | jq -r .protocol)
          PROVIDER_SNI=$(echo $provider | jq -r .sni)
          if [ "${PROVIDER_PROTO}" == "https" ]
          then
            if [ ! -z "${PROVIDER_SNI}" ]
            then
              SNI_FQDN=${PROVIDER_SNI}
            else
              SNI_FQDN=${INGRESS_DOMAIN}
            fi
            CHECK="check ssl verify none check-sni ${INGRESS_DOMAIN} sni str(${SNI_FQDN})"
          else
            CHECK="check"
          fi
          echo "    server ${PROVIDER_NAME}    ${PROVIDER_HOST}:${PROVIDER_PORT} ${CHECK} maxconn ${HAPROXY_MAXCONN_PER_BACKEND} cookie core"
        done > /tmp/${FQDN}.backends.haproxy.cfg
        
      
        cat > /tmp/${FQDN}.haproxy.cfg <<EOF
      backend ${FQDN} 
        mode http
        balance static-rr

        $(envsubst < ${HEALTHCHECKS_TEMPLATE_DIR}/${api}-healthcheck.tpl)
    
        cookie network insert
        http-request set-header X-Client-IP %[src]
        http-request set-header X-Forwarded-Host %[req.hdr(Host)]
        http-request set-header Origin https://${INGRESS_DOMAIN}
        http-request set-header Host ${INGRESS_DOMAIN}
    
    $(cat /tmp/${FQDN}.backends.haproxy.cfg)
    
    EOF

      cat /tmp/${FQDN}.haproxy.cfg >> ${CONFIG_OUTPUT_DIR}/dandelion-haproxy.cfg
      done
    done
