apiVersion: v1
kind: ConfigMap
metadata:
  name: ogmios-configmap
data:
  initContainer-entrypoint: |
    rm -rf /config/lost+found

    CNODE_FILES="config.json byron-genesis.json genesis.json alonzo-genesis.json"

    for file in ${CNODE_FILES}
    do
      cp -a /opt/cardano/cnode/files/${file} /config
    done
