apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
data:
  POSTGRES_HOST: init0-postgresql-ha-pgpool
  POSTGRES_HOST_RO: init0-postgresql-ha-pgpool
  POSTGRES_HOST_RW: init0-postgresql-ha-pgpool
  POSTGRES_PORT: "5432"
  POSTGRES_DB: cdbs
  POSTGRES_USER: postgres
  POSTGREST_USER_RO:  postgrest_ro
  chisel-auth-file: |
    {
      "admin:CHANGEME": [""]
    }
